### ISSUE TITLE
大佬新版本启动不了

### ISSUE THREAD

**Issue by graytoowolf** [snnyyp/AuthlibInjectorWrapper#2]
![image](https://user-images.githubusercontent.com/57069542/218259168-26283544-f153-48a5-aae1-455ae648fba8.png)

启动参数带上-Xms  -Xmx  这俩就启动不了报错

**Comment by snnyyp** [comment]
可别叫我大佬，你这么一说，我就想到这个项目几年前的屎山代码，怪不好意思的

JVM无法传参的问题，是因为我没有做足够的测试，完全算我的锅
最新的提交解决了这个问题，以及连带发现的一些潜在的问题。你拉取一下更新，重新构建再看看
凌晨了，你的Forge的问题今天早上我再研究研究

**Comment by graytoowolf** [comment]
ok  感谢
